version: '3.9'

services:
  app:
    build: .
    ports:
      - "${APP_PORT:-3000}:${APP_PORT:-3000}"
    environment:
      NEO4J_URI: 'neo4j://${NEO4J_HOST:-neo4j}:${NEO4J_PORT:-7687}'
      NEO4J_USER: "${NEO4J_USER:-neo4j}"
      NEO4J_PASSWORD: "${NEO4J_PASSWORD:-password}"
    depends_on:
      - neo4j
    volumes:
      - .:/app
      - node_modules:/app/node_modules
  neo4j:
    image: neo4j:latest
    environment:
      NEO4J_AUTH: "${NEO4J_USER:-neo4j}/${NEO4J_PASSWORD:-password}"
    volumes:
      - neo4j_data:/data
    ports:
      - "${NEO4J_HTTP_PORT:-7474}:7474"
      - "${NEO4J_BOLT_PORT:-7687}:7687"

volumes:
  neo4j_data:
  node_modules: